# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/conf.py

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf
  
# setting up build.os and the python version
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - method: pip
      path: .
    - requirements: doc/requirements.txt
