[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
select = [
  "A",
  "ARG",
  "B",
  "C",
  "DTZ",
  "E",
  "EM",
  "F",
  "FBT",
  "I",
  "ICN",
  "ISC",
  "N",
  "PLC",
  "PLE",
  "PLR",
  "PLW",
  "Q",
  "RUF",
  "S",
  "T",
  "TID",
  "UP",
  "W",
  "YTT",
]
unfixable = [
  # Don't touch unused imports
  "F401",
]
ignore = [
  # Ignore complexity
  "PLR0913",
]

[tool.ruff.isort]
known-first-party = ["amazon_braket_sdk"]

[tool.ruff.flake8-tidy-imports]
ban-relative-imports = "all"
