[tool.black]
line-length = 100

[tool.ruff]
# 3.10 introduces standards such as PEP604 which changes lots of typing
target-version = "py39"
line-length = 100
select = [
  "A",
  "ARG",
  "B",
  "C",
  "DTZ",
  "E",
  "F",
  "FBT",
  "I",
  "ICN",
  "ISC",
  "N",
  "PLC",
  "PLE",
  "PLR",
  "PLW",
  "Q",
  "RUF",
  "S",
  "T",
  "TID",
  "UP",
  "W",
  "YTT",
]
unfixable = [
  # Don't touch unused imports
  "F401",
]
ignore = [
  # Python 3.10 and later rule
  "UP007",
  # Magic vars. Should be enabled later.
  "PLR2004",
  # Ignore complexity
  "PLR0913",
  # Uppercase function names are fine in some cases
  "N802",
]

[tool.ruff.isort]
known-first-party = ["amazon_braket_sdk"]

[tool.ruff.flake8-tidy-imports]
ban-relative-imports = "all"
