[tool.black]
line-length = 100

[tool.ruff]
# 3.10 introduces standards such as PEP604 which changes lots of typing
target-version = "py39"
line-length = 100
select = [
  "A",
  "ANN",
  "ARG",
  "B",
  "C",
  "D",
  "DTZ",
  "E",
  "F",
  "I",
  "ICN",
  "ISC",
  "N",
  "PLC",
  "PLE",
  "PLR",
  "PLW",
  "Q",
  "RUF",
  "S",
  "T",
  "TID",
  "UP",
  "W",
  "YTT",
]
unfixable = [
  # Don't touch unused imports
  "F401",
]
ignore = [
  # Checking the type for self, special methods is not needed
  # Allow dynamic typing
  "ANN101", "ANN102", "ANN204", "ANN401",
  # Docstrings are all written within classes and modules
  # No needed docstrings for classes/magic methods.
  # No summary lines
  "D100", "D101", "D102", "D105", "D107", "D205", "D415",
  # Python 3.10 and later rule
  "UP007",
  # Magic vars. Should be enabled later.
  "PLR2004",
  # Ignore complexity
  "PLR0913",
  # Uppercase function names are fine in some cases
  "N802", "N806",
  # Allow Optional return types
  "RUF013",
]

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.isort]
known-first-party = ["amazon_braket_sdk"]

[tool.ruff.flake8-tidy-imports]
ban-relative-imports = "all"
