[tox]
env_list = clean, linters, docs, unit-tests

[testenv]
package = wheel
wheel_build_env = .pkg

[testenv:clean]
deps = coverage
skip_install = true
commands = coverage erase

[testenv:unit-tests]
usedevelop = true
extras = test
# {posargs} contains additional arguments specified when invoking tox. e.g. tox -- -s -k test_foo.py
deps =
    {[test-deps]deps}
commands =
    pytest {posargs} --cov --cov-report=term-missing --cov-report=html --cov-report=xml --cov-append

[testenv:integ-tests]
extras = test
# {posargs} contains additional arguments specified when invoking tox. e.g. tox -- -s -k test_foo.py
deps =
    {[test-deps]deps}
pass_env =
    AWS_PROFILE
    AWS_REGION
    BRAKET_ENDPOINT
commands =
    pytest test/integ_tests {posargs}

[testenv:linters]
skip_install = true
deps =
    {[testenv:ruff-format]deps}
    {[testenv:ruff-check]deps}
commands =
    {[testenv:ruff-format]commands}
    {[testenv:ruff-check]commands}

# Read only linter env
[testenv:linters_check]
skip_install = true
deps =
    {[testenv:ruff-check]deps}
commands =
    ruff format --check . {posargs}
    {[testenv:ruff-check]commands}

[testenv:ruff-check]
skip_install = true
deps =
    ruff
commands =
    ruff check src {posargs}

[testenv:ruff-format]
skip_install = true
deps =
    ruff
commands =
    ruff format . {posargs}

[testenv:docs]
extras = docs
deps =
    {[test-deps]deps}
    m2r2
commands =
    sphinx-build -E -T -b html doc build/documentation/html -j auto

[testenv:serve-docs]
skip_install = true
changedir = build/documentation/html
commands =
    python -m http.server {posargs}

[testenv:zip-build]
skip_install = true
commands =
    /bin/sh -c 'tar -czvf build_files.tar.gz build/'

[test-deps]
deps =
    # If you need to test on a certain branch, add @<branch-name> after .git
    git+https://github.com/amazon-braket/amazon-braket-schemas-python.git
    git+https://github.com/amazon-braket/amazon-braket-default-simulator-python.git
