
# reduced_ionq_device_capabilities = {'action': {'braket.ir.openqasm.program': {'actionType': 'braket.ir.openqasm.program',
#                                                                         'supportedOperations': [],
#                                                                         "supportedResultTypes": valid_supportedResultTypes,
#                                                                         'version': ['1']}
#                                                                         },
#  'braketSchemaHeader': {'name': 'braket.device_schema.ionq.ionq_device_capabilities',
#                         'version': '1'},
#  'deviceParameters': {},
#  'paradigm': {'braketSchemaHeader': {'name': 'braket.device_schema.gate_model_qpu_paradigm_properties',
#                                      'version': '1'},
#               'connectivity': {'connectivityGraph': {}, 'fullyConnected': True},
#               'nativeGateSet': ['GPI', 'GPI2', 'MS'],
#               'qubitCount': 25},
#  'provider': {'braketSchemaHeader': {'name': 'braket.device_schema.ionq.ionq_provider_properties',
#                                      'version': '1'},
#               'errorMitigation': {'braket.device_schema.error_mitigation.debias.Debias': {'minimumShots': 2500}},
#               'fidelity': {'1Q': {'mean': 0.9998},
#                            '2Q': {'mean': 0.9872},
#                            'spam': {'mean': 0.9937}},
#               'timing': {'1Q': 0.000135,
#                          '2Q': 0.0006,
#                          'T1': 100.0,
#                          'T2': 1.0,
#                          'readout': 0.0003,
#                          'reset': 2e-05}},
#     "service": {
#         "braketSchemaHeader": {
#             "name": "braket.device_schema.device_service_properties",
#             "version": "1",
#         },
#         "executionWindows": [],
#         "shotsRange": [1, 20000],
#     },
#              }
